# Generated by Django 6.0.5 on 2026-05-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('estado', models.CharField(default='Abierta', max_length=50)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_incidencias.ciudadano')),
            ],
        ),
    ]
