# Generated by Django 6.0.5 on 2026-05-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN REVISION', 'En revision'), ('REVISADO', 'Revisado')], default='PENDIENTE', max_length=20),
        ),
    ]
